DROP TABLE IF EXISTS USER;
 
CREATE TABLE USER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  userName VARCHAR(250) NOT NULL,
  firstName VARCHAR(250) NOT NULL,
  lastName VARCHAR(250) NOT NULL,
  age NUMBER NOT NULL,
  salary NUMBER NOT NULL
);
