DROP TABLE IF EXISTS USER;
 
CREATE TABLE USER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  user_name VARCHAR(250) NOT NULL,
  password VARCHAR(10) NOT NULL,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  age NUMBER NOT NULL,
  salary NUMBER NOT NULL
);
